### PR TITLE
ZIMBRA-114: "events" configset

### PR DESCRIPTION
**Pull request by ilyusha**
New solr configset used for indexing events.

#### Schema
 - `id` is the required event ID. It is constructed based on the _UniqueOn_ value of the _EventType_.
 - `ev_type` is the event type
 - `ev_timestamp` is the date-formatted timestamp of the event
 - `msg_id` is id of the message this event associated with
 - `acct_id` is the account ID associated with the event. This is only used when events are stored in a combined index.
 - `datasource_id` is the optional ID of the data source of the message the event was triggered for

#### Config
The notable addition here is the "skipexisting" update request processor chain. It uses Solr's built-in _SkipExistingDocumentsProcessorFactory_ to skip indexing documents for which the ID already exists in the index.

### CODE REVIEW

**Comment by fatkudu** [comment]
Is this based on an original source file in SOLR?  It may be better for future maintenance if we store that file as is in a template then store a script which makes the Zimbra modifications or even a patch file to do that?

**Review by tmclane — APPROVED** [review]
I agree with @fatkudu regarding templatizing this file if possible.  

Possible methods: 
https://issues.apache.org/jira/browse/SOLR-3087

Or add resources as external entities:
```

<?xml version="1.0" encoding="UTF-8" ?> 
<!DOCTYPE schema [
     <!ENTITY schemafieldtypes SYSTEM "schemafieldtypes.xml"> 
]> 
```

```

Use it in the XML file like so:
&schemafieldtypes;

```

Note: Examples come from stackoverflow.

**Comment by ilyusha** [comment]
Actually, what might be even better is to use solr's schema API to generate the schema:
https://lucene.apache.org/solr/guide/6_6/schema-api.html#schema-api

My priority with this initial work was to get event indexing working; I think schema improvements could go under a separate bug.

**Review by fatkudu — APPROVED** [review]

**Review by grishick — APPROVED** [review]
I guess this is fine as the first pass, but I'd prefer that you remove all the default commented out content, because it is distracting.

**Review by fatkudu — APPROVED** [review]

**Review by gordyt — APPROVED** [review]
Looks good.  After this is merged I should update the solr image right?

**Pull request merged**
